name: future_manager
description: ValueNotifier and ValueListenableBuilder but for asynchronous value.
version: 1.0.0
homepage: https://github.com/asurraa/sura_manager

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
flutter:
